[package]
name = "recurrence"
version = "0.0.1"
authors = ["Andrés Medina <andresnrx@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "^0.4"
chrono-tz = "0.5"
iana-time-zone = "^0.1"

[dev-dependencies]
approx = "0.3.2"
